const questions = [
  {
    question: "1. شنو تحسّ روحك تهرب منو؟",
    options: ["الوجيعة", "المسؤولية", "الروتين"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "2. وقت اللي تكون وحدك، شنو يدور في مخّك؟",
    options: ["ذكريات", "خطط للمستقبل", "فراغ"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "3. شنو الحاجة اللي عمر ما حد فهمها فيك؟",
    options: ["طريقتي في التفكير", "ردة فعلي", "سكوتي"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "4. تحب تتحكّم ولا تتسيّب؟",
    options: ["نتحكّم", "نخلّيها تمشي", "حسب الحالة"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "5. شنو النوع متاع الغموض اللي يجذبك؟",
    options: ["الأشخاص", "الأماكن", "القصص"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "6. كي تغلط، شنو أول إحساس يجيك؟",
    options: ["ندم", "غضب من روحي", "برود"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "7. شنو يخوّفك أكثر: الفقدان ولا التكرار؟",
    options: ["الفقدان", "التكرار", "الزوز"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "8. لو تنجم تمحي حاجة من ذاكرتك، شنوة تكون؟",
    options: ["شخص", "موقف", "فترة"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "9. شنو يعني ليك الصمت؟",
    options: ["راحة", "هروب", "رسالة"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "10. تحس روحك زادة تتخبّى ورا شنو؟",
    options: ["الضحكة", "الصمت", "الكره"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "11. شنو نوع التعب اللي ما ينشافش؟",
    options: ["نفسي", "عقلي", "عاطفي"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "12. شنو الحاجة اللي تغيّرك بلا ما تحس؟",
    options: ["الخذلان", "الانتظار", "الوحدة"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "13. شنو اللي يربطك بالناس؟",
    options: ["العقل", "الإحساس", "الفايدة"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "14. وقت اللي تكون غارق، شنو أول حاجة تتمسّك بيها؟",
    options: ["الأمل", "شخص", "لاشي"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "15. شنو أصعب قرار خذيتو بقلب بارد؟",
    options: ["قطع علاقة", "تجاهل", "اعتراف"],
    scores: [30, 60, 90],
    selectedIndex: null,
  },
  {
    question: "16. اشرح مشكلتك",
    type: "text",
    answer: "",
  },
];
